Universidad3/urls.py
from django.contrib import admin
from django.urls import path 

from gestioncursos import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="Home"),
    path('home', views.home, name="Home"),
    path('cursos/', include('cursos.urls')),
    path('carro/', include('carro.urls')),
    path('conocenos/', include('conocenos.urls')),
    path('aspirante', views.aspirante, name="Aspirante"),
    path('contacto/', include('contacto.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('asignaciones/', include('asignaciones.urls')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

carro/urls.py
from django.urls import path 
from . import views

app_name="carro"

urlpatterns = [
    
    path("agregar/<int:curso_id>/", views.agregar_curso, name="agregar"),
    path("eliminar/<int:curso_id>/", views.eliminar_curso, name="eliminar"),
    path("restar/<int:curso_id>/", views.restar_curso, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),

]

cursos/urls.py
from django.urls import path 
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', views.cursos, name="Cursos"),
    path('exito', views.exito, name="Exito"),
    path('categoriacurso/<int:categoriacurso_id>/', views.categoriacurso, name="categoriacurso"),

]

carro/models.py
from django.db import models

# Create your models here.

cursos/models.py
from django.db import models

# Create your models here.

class CategoriaCurso(models.Model):
    nombre=models.CharField(max_length=30)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='categoriaCurso'
        verbose_name_plural='categoriasCurso'

    def __str__(self):
        return self.nombre
    
class Curso(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(CategoriaCurso, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to='cursos', null=True, blank=True)
    creditos=models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name='Curso'
        verbose_name_plural='Cursos'

    def __str__(self):
        return self.nombre

carro/views.py
from django.shortcuts import render
from .carro import Carro
from cursos.models import Curso
from django.shortcuts import redirect
# Create your views here.

def agregar_curso(request, curso_id):
    carro=Carro(request)
    curso=Curso.objects.get(id=curso_id)
    carro.agregar(curso=curso)
    return redirect("Cursos")

def eliminar_curso(request, curso_id):
    carro=Carro(request)
    curso=Curso.objects.get(id=curso_id)
    carro.eliminar(curso=curso)
    return redirect("Cursos")

def restar_curso(request, curso_id):
    carro=Carro(request)
    curso=Curso.objects.get(id=curso_id)
    carro.restar_curso(curso=curso)
    return redirect("Cursos")

def limpiar_carro(request, curso_id):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect("Cursos")

cursos/views.py
from django.shortcuts import render
from .models import Curso, CategoriaCurso

# Create your views here.

def cursos(request):

    cursos=Curso.objects.all()

    return render(request, "cursos/cursos.html", {"cursos": cursos})

def exito(request):

    
    return render(request, "cursos/exito.html", {"cursos": cursos})


def categoriacurso(request, categoriacurso_id):

    categoriacurso=CategoriaCurso.objects.get(id=categoriacurso_id)
    cursos=Curso.objects.filter(categoriascurso=categoriacurso)
    return render(request, "cursos/categoriacurso.html", {'categoriacurso':categoriacurso,"cursos": cursos })

cursos/templates/carro/widget.html
<table class="table table-bordered" style="color: white;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Registro de Asignación

            </th>
        </tr>
        <tr>
            <th>Curso</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>


    </thead>
    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.curso_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.curso_id %}" class="btn btn-sm btn-success">-</a><br/>

                        {{value.creditos}}
                    </td>
                </tr>

            {% endfor%}
        {% else%}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin cursos
                    </div>
                </td>


            </tr>    
        {% endif %}

    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total créditos asignados: {{importe_total}}

            </td>
        </tr>
        {% if request.session.carro.items %}
        <tr>
            <td colspan="3" style="text-align: center;">
                <a href="../asignaciones" class="btn btn-success">Confirmar Asignación</a>
            
            </td>

        </tr>
        {% endif %}
    </tfoot>


</table>